version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
      - ./sql/initial-election-database.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - backend
  
  nestjs-election-api:
    depends_on:
      - mysqldb
    build: 
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    networks:
      - backend
  
volumes: 
  db:
networks:
  backend: